#!/bin/sh
###############################################################
# This script was created by: MDK - mdk@thecoreme.org         #
# http://projects.thecoreme.org/                              #
# Jul 10 2013                                                 #
# Last update on Aug 11 2016                                  #
#                                                             #
# Simple script to update git repositories on the current dir #
###############################################################

WORKDIR=$PWD
cd $WORKDIR

echo "Updating git repositories..."
for each in `ls -d */ -1`
do
    cd $each
        echo "\n\t - $each"
        git rev-parse HEAD
        git remote update && git pull --rebase --prune
        git submodule update --init
    cd $WORKDIR
done

echo "\ngit repos are updated now"
