#!/bin/sh
###############################################################
# This script was created by: MDK - mdk@qtrnn.io              #
# https://qtrnn.io                                            #
# Jul 10 2013                                                 #
# Last update on Oct 20 2020                                  #
#                                                             #
# Simple script to update git repositories (and its           #
# submodules) on the current dir                              #
###############################################################

echo "Updating git repositories..."
for each in ./*/
do
    (
        cd "$each" || exit
        echo "- $(basename "$each")"

        git rev-parse HEAD
        git remote update

        git submodule update --init --recursive
        git pull --rebase --prune --tags

        echo
    )
done

echo
echo "git repositories are updated now"
